[pytest]
addopts = -q --tb=line --video=retain-on-failure

; -s
; -showlocals
; -r short test summary info
; PYTEST_DEBUG=0
; --disable-warnings
; PWDEBUG=0

; FLAGS MAPEADAS:

; headed/headless: Rodar os testes mostrando o navegador ou não.

; reruns=n: Rodar novamente testes que falharam, até sucederem ou n vezes, o que vier primeiro.

; verbosity: Saída geral, principalmente sumário.
; -qq: Apenas os testes que falharam, e o motivo do erro;
; -q: Passa a informar a contagem de testes para cada status;
; default: Passa a informar sobre o ambiente de testes
; -v: Passa a informar o caminho do cache e do Python.

; tb: Traceback, o caminho até a linha que deu erro.
; no: Não informa nada sobre a falha;
; line: Informa o caminho e o erro;
; short: Passa a informar o nome do teste separado e a linha de erro
; long: Passa a informar o navegador e a função até a linha de falha